import { MigrationInterface, QueryRunner } from "typeorm";

export class userSignupFlow1664313032991 implements MigrationInterface {
    name = 'userSignupFlow1664313032991'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3"`);
        await queryRunner.query(`ALTER TABLE "email" DROP CONSTRAINT "FK_13e97b4a1d6074fd75ea1bb844e"`);
        await queryRunner.query(`ALTER TABLE "page_content" DROP CONSTRAINT "FK_4e28fda8b4d802c7e7a3e8c03e2"`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" DROP CONSTRAINT "FK_87ea0bdd649b119d842f233ab37"`);
        await queryRunner.query(`ALTER TABLE "workspace" DROP CONSTRAINT "FK_51f2194e4a415202512807d2f63"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "FK_3e419598ba888095f081633c512"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "FK_181d08bb1a292753ad89ec74ea7"`);
        await queryRunner.query(`ALTER TABLE "user_preference" DROP CONSTRAINT "FK_5b141fbd1fef95a0540f7e7d1e2"`);
        await queryRunner.query(`ALTER TABLE "audit_entry" DROP CONSTRAINT "FK_3a69a645488fcd51f01d6f85d80"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "firstName" character varying, "lastName" character varying, "nickName" character varying, "birthday" TIMESTAMP, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workspace_admins_users" ("workspaceId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_e5cd914c8c7377ea29681e16e8b" PRIMARY KEY ("workspaceId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e04e1791cb2a66b4507dde900f" ON "workspace_admins_users" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f949238513c58172cb6ba27854" ON "workspace_admins_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "workspace_members_users" ("workspaceId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_24e3b6dcb497f2c8e5bcf690a16" PRIMARY KEY ("workspaceId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9af0540a8615e6be0d9c779982" ON "workspace_members_users" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_face80c6a346b5a80184075716" ON "workspace_members_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "workspace_visitors_users" ("workspaceId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_342e8dc63c765f71125594f9e12" PRIMARY KEY ("workspaceId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9399bc95515c7e12d5c5c75d15" ON "workspace_visitors_users" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_663bfaa90e9c6d890a9de03f6e" ON "workspace_visitors_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "page_admins_users" ("pageId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_1e0dd4f7cbb66e592d4868a73d5" PRIMARY KEY ("pageId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f4887782c0ba3b3ce8b0947e7" ON "page_admins_users" ("pageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1f2e43901074c06afefc488a0" ON "page_admins_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "page_members_users" ("pageId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_5c529c8d2a808bc8ca3cf6207ca" PRIMARY KEY ("pageId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05c343ecd147a70eecb424980d" ON "page_members_users" ("pageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0cab4dbbedf8430e80ed848b5" ON "page_members_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "page_visitors_users" ("pageId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_3e83e2d7c60859e438dfb99830e" PRIMARY KEY ("pageId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_825070f1a34e59cc588b4f30ff" ON "page_visitors_users" ("pageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba5fed66b0ebe13a149a3c4db5" ON "page_visitors_users" ("usersId") `);
        await queryRunner.query(`ALTER TABLE "page_content" ADD "contentElementId" uuid`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" DROP COLUMN "option"`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" ADD "option" "public"."workspace_preference_option_enum" NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."audit_entry_type_enum" RENAME TO "audit_entry_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_entry_type_enum" AS ENUM('user_signup_init', 'user_signup_complete', 'user_signup_failed', 'user_signin', 'user_inconsistent_signup', 'user_email_verified', 'user_email_verification_failed', 'user_deleted')`);
        await queryRunner.query(`ALTER TABLE "audit_entry" ALTER COLUMN "type" TYPE "public"."audit_entry_type_enum" USING "type"::"text"::"public"."audit_entry_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_entry_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email" ADD CONSTRAINT "FK_13e97b4a1d6074fd75ea1bb844e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_content" ADD CONSTRAINT "FK_4e28fda8b4d802c7e7a3e8c03e2" FOREIGN KEY ("pageId") REFERENCES "page"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_content" ADD CONSTRAINT "FK_ac0e9a8572eb1afcf6294b482a9" FOREIGN KEY ("contentElementId") REFERENCES "content_element"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" ADD CONSTRAINT "FK_87ea0bdd649b119d842f233ab37" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace" ADD CONSTRAINT "FK_51f2194e4a415202512807d2f63" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "FK_3e419598ba888095f081633c512" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "FK_181d08bb1a292753ad89ec74ea7" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preference" ADD CONSTRAINT "FK_5b141fbd1fef95a0540f7e7d1e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_entry" ADD CONSTRAINT "FK_3a69a645488fcd51f01d6f85d80" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_admins_users" ADD CONSTRAINT "FK_e04e1791cb2a66b4507dde900f9" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workspace_admins_users" ADD CONSTRAINT "FK_f949238513c58172cb6ba278543" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members_users" ADD CONSTRAINT "FK_9af0540a8615e6be0d9c7799828" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workspace_members_users" ADD CONSTRAINT "FK_face80c6a346b5a80184075716e" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_visitors_users" ADD CONSTRAINT "FK_9399bc95515c7e12d5c5c75d153" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workspace_visitors_users" ADD CONSTRAINT "FK_663bfaa90e9c6d890a9de03f6e5" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_admins_users" ADD CONSTRAINT "FK_0f4887782c0ba3b3ce8b0947e7e" FOREIGN KEY ("pageId") REFERENCES "page"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "page_admins_users" ADD CONSTRAINT "FK_d1f2e43901074c06afefc488a03" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_members_users" ADD CONSTRAINT "FK_05c343ecd147a70eecb424980de" FOREIGN KEY ("pageId") REFERENCES "page"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "page_members_users" ADD CONSTRAINT "FK_a0cab4dbbedf8430e80ed848b5b" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_visitors_users" ADD CONSTRAINT "FK_825070f1a34e59cc588b4f30ffd" FOREIGN KEY ("pageId") REFERENCES "page"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "page_visitors_users" ADD CONSTRAINT "FK_ba5fed66b0ebe13a149a3c4db54" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "page_visitors_users" DROP CONSTRAINT "FK_ba5fed66b0ebe13a149a3c4db54"`);
        await queryRunner.query(`ALTER TABLE "page_visitors_users" DROP CONSTRAINT "FK_825070f1a34e59cc588b4f30ffd"`);
        await queryRunner.query(`ALTER TABLE "page_members_users" DROP CONSTRAINT "FK_a0cab4dbbedf8430e80ed848b5b"`);
        await queryRunner.query(`ALTER TABLE "page_members_users" DROP CONSTRAINT "FK_05c343ecd147a70eecb424980de"`);
        await queryRunner.query(`ALTER TABLE "page_admins_users" DROP CONSTRAINT "FK_d1f2e43901074c06afefc488a03"`);
        await queryRunner.query(`ALTER TABLE "page_admins_users" DROP CONSTRAINT "FK_0f4887782c0ba3b3ce8b0947e7e"`);
        await queryRunner.query(`ALTER TABLE "workspace_visitors_users" DROP CONSTRAINT "FK_663bfaa90e9c6d890a9de03f6e5"`);
        await queryRunner.query(`ALTER TABLE "workspace_visitors_users" DROP CONSTRAINT "FK_9399bc95515c7e12d5c5c75d153"`);
        await queryRunner.query(`ALTER TABLE "workspace_members_users" DROP CONSTRAINT "FK_face80c6a346b5a80184075716e"`);
        await queryRunner.query(`ALTER TABLE "workspace_members_users" DROP CONSTRAINT "FK_9af0540a8615e6be0d9c7799828"`);
        await queryRunner.query(`ALTER TABLE "workspace_admins_users" DROP CONSTRAINT "FK_f949238513c58172cb6ba278543"`);
        await queryRunner.query(`ALTER TABLE "workspace_admins_users" DROP CONSTRAINT "FK_e04e1791cb2a66b4507dde900f9"`);
        await queryRunner.query(`ALTER TABLE "audit_entry" DROP CONSTRAINT "FK_3a69a645488fcd51f01d6f85d80"`);
        await queryRunner.query(`ALTER TABLE "user_preference" DROP CONSTRAINT "FK_5b141fbd1fef95a0540f7e7d1e2"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "FK_181d08bb1a292753ad89ec74ea7"`);
        await queryRunner.query(`ALTER TABLE "page" DROP CONSTRAINT "FK_3e419598ba888095f081633c512"`);
        await queryRunner.query(`ALTER TABLE "workspace" DROP CONSTRAINT "FK_51f2194e4a415202512807d2f63"`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" DROP CONSTRAINT "FK_87ea0bdd649b119d842f233ab37"`);
        await queryRunner.query(`ALTER TABLE "page_content" DROP CONSTRAINT "FK_ac0e9a8572eb1afcf6294b482a9"`);
        await queryRunner.query(`ALTER TABLE "page_content" DROP CONSTRAINT "FK_4e28fda8b4d802c7e7a3e8c03e2"`);
        await queryRunner.query(`ALTER TABLE "email" DROP CONSTRAINT "FK_13e97b4a1d6074fd75ea1bb844e"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_entry_type_enum_old" AS ENUM('user_signup_init', 'user_signup_complete', 'user_signup_failed', 'user_signin', 'user_inconsistent_signup', 'user_email_verified', 'user_email_verification_failed')`);
        await queryRunner.query(`ALTER TABLE "audit_entry" ALTER COLUMN "type" TYPE "public"."audit_entry_type_enum_old" USING "type"::"text"::"public"."audit_entry_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."audit_entry_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_entry_type_enum_old" RENAME TO "audit_entry_type_enum"`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" DROP COLUMN "option"`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" ADD "option" workspace_preference_option_enum NOT NULL`);
        await queryRunner.query(`ALTER TABLE "page_content" DROP COLUMN "contentElementId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba5fed66b0ebe13a149a3c4db5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_825070f1a34e59cc588b4f30ff"`);
        await queryRunner.query(`DROP TABLE "page_visitors_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0cab4dbbedf8430e80ed848b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05c343ecd147a70eecb424980d"`);
        await queryRunner.query(`DROP TABLE "page_members_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1f2e43901074c06afefc488a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f4887782c0ba3b3ce8b0947e7"`);
        await queryRunner.query(`DROP TABLE "page_admins_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_663bfaa90e9c6d890a9de03f6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9399bc95515c7e12d5c5c75d15"`);
        await queryRunner.query(`DROP TABLE "workspace_visitors_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_face80c6a346b5a80184075716"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9af0540a8615e6be0d9c779982"`);
        await queryRunner.query(`DROP TABLE "workspace_members_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f949238513c58172cb6ba27854"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e04e1791cb2a66b4507dde900f"`);
        await queryRunner.query(`DROP TABLE "workspace_admins_users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "audit_entry" ADD CONSTRAINT "FK_3a69a645488fcd51f01d6f85d80" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preference" ADD CONSTRAINT "FK_5b141fbd1fef95a0540f7e7d1e2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "FK_181d08bb1a292753ad89ec74ea7" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page" ADD CONSTRAINT "FK_3e419598ba888095f081633c512" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace" ADD CONSTRAINT "FK_51f2194e4a415202512807d2f63" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_preference" ADD CONSTRAINT "FK_87ea0bdd649b119d842f233ab37" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_content" ADD CONSTRAINT "FK_4e28fda8b4d802c7e7a3e8c03e2" FOREIGN KEY ("pageId") REFERENCES "page"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email" ADD CONSTRAINT "FK_13e97b4a1d6074fd75ea1bb844e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
