import { PONG, USER_DELETE, USER_GET, WORKSPACE_PUT, WORKSPACE_WORKSPACEID_GET, WORKSPACE_WORKSPACEID_DELETE } from './secure';

export const V1 = '/v1';
export const PING = '/ping';
export const SECURE = '/secure';

export const SECURE_PONG = SECURE + PONG;
export const SECURE_USER_GET = SECURE + USER_GET;
export const SECURE_USER_DELETE = SECURE + USER_DELETE;
export const SECURE_WORKSPACE_WORKSPACEID_GET = SECURE + WORKSPACE_WORKSPACEID_GET;
export const SECURE_WORKSPACE_PUT = SECURE + WORKSPACE_PUT;
export const SECURE_WORKSPACE_WORKSPACEID_DELETE = SECURE + WORKSPACE_WORKSPACEID_DELETE;
