name: lumium-renderer-unit

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: WASM Pack Build
      run: cd lumium-space/lumium-renderer && wasm-pack build
    - name: Cargo Build
      run: cd lumium-space/lumium-renderer && cargo build --verbose
    - name: Run tests
      run: cd lumium-space/lumium-renderer && cargo test --verbose
