name: space-e2e

on:
    push:
    pull_request:

env:
    CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL }}
    CYPRESS_TEST_USER_PASS: ${{ secrets.CYPRESS_TEST_USER_PASS }}
    SUPERTOKENS_API_KEY: ${{ secrets.SUPERTOKENS_API_KEY }}
    SUPERTOKENS_CONNECTION_URI: ${{ secrets.SUPERTOKENS_CONNECTION_URI }}


jobs:
    e2e:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16]

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  submodules: 'recursive'

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: wasm-pack-action
              uses: jetli/wasm-pack-action@v0.3.0

            - name: Install dependencies
              run: yarn

            - name: Run end-to-end tests
              run: cd lumium-space && yarn run cypress:test
