name: tests

on:
    push:
        branches:
          - develop
          - master
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16]
        services:
          postgres:
            image: postgres:latest
            env:
              POSTGRES_DB: lumium_test
              POSTGRES_PASSWORD: development
              POSTGRES_PORT: 5432
              POSTGRES_USER: development
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  submodules: 'recursive'
            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}
            - name: Run tests
              run: make test
