### sign up

POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "someone@gmail.com",
  "username": "someone",
  "password": "qwerty12345"
}

### sign in

POST http://localhost:3000/signin
Content-Type: application/json

{
  "username_or_email": "someone@gmail.com",
  "password": "qwerty12345"
}

### sign out

POST http://localhost:3000/signout

###
